spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
          endpoint: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net